{% set name = "azure-mgmt-msi" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 8622bc9a164169a0113728ebe7fd43a88189708ce6e10d4507247d6907987167

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - azure-common >=1.1,<2
    - msrestazure >=0.4.27,<2.0.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.msi
    - azure.mgmt.msi.models
    - azure.mgmt.msi.operations

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure MSI Management Client Library for Python
  doc_url: https://docs.microsoft.com/python/api/overview/azure/activedirectory
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
