schema_version: 1

context:
  name: azure-mgmt-msi
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: 8622bc9a164169a0113728ebe7fd43a88189708ce6e10d4507247d6907987167

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - azure-common >=1.1,<2
    - msrestazure >=0.4.27,<2.0.0
    - python

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.msi
        - azure.mgmt.msi.models
        - azure.mgmt.msi.operations
      pip_check: false

      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure MSI Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://docs.microsoft.com/python/api/overview/azure/activedirectory

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
    - janjagusch
