schema_version: 1

context:
  name: azure-mgmt-msi
  version: 7.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: 72d46c9a62783ec4eab619be9d1b78ffebbdaa164d406fd303f16303f37256b2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1.0,<2.0.0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - msrest >=0.7.1

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.msi
        - azure.mgmt.msi.models
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure MSI Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://docs.microsoft.com/python/api/overview/azure/activedirectory

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
    - janjagusch
